sudo: required
services:
  - docker

before_install:
  - docker build -t thephilgray/docker-and-kubernetes-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thephilgray/docker-and-kubernetes-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-and-kubernetes-react
  env: DockerAndKubernetesReact-env
  bucket_name: elasticbeanstalk-us-east-1-856562418824
  bucket_path: docker-and-kubernetes-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
